### ISSUE TITLE
Add a git ignore file

### ISSUE THREAD

**Issue by templth** [spicypig/carpool#1]
You shouldn't include folders like `node_modules` in your repository since this can be generate using the command `npm install`.

For this simply add a file `.gitignore` as the root of your repository with the following content:

    node_modules/
    npm-debug.log

You can then add new entries according to your needs.

**Comment by spicypig** [comment]
How to remove the previous node_modules folder that already committed to the repo?

**Comment by templth** [comment]
Just remove the folder in your local repository and then commit the updates. Using the command `git status`, we can see what to commit...
