### ISSUE TITLE
Post /users return error in Postman

### ISSUE THREAD

**Issue by spicypig** [spicypig/carpool#2]
As sent this in Postman in JSON format for HTTP POST request to create a new user: 
```json
{
    "email": "test@test.com”,
    "name": "Chuan",
    "location": {
      "latitude": 3333,
      "longitude": 111
     }, 
    "details": {
      "firstName": Chuan
      "lastName": He
    }
  }
```

But I see errors:
```
{
    "message": "User validation failed",
    "name": "ValidationError",
    "errors": {
        "email": {
            "properties": {
                "type": "required",
                "message": "Path `{PATH}` is required.",
                "path": "email"
            },
            "message": "Path `email` is required.",
            "name": "ValidatorError",
            "kind": "required",
            "path": "email"
        },
        "name": {
            "properties": {
                "type": "required",
                "message": "Path `{PATH}` is required.",
                "path": "name"
            },
            "message": "Path `name` is required.",
            "name": "ValidatorError",
            "kind": "required",
            "path": "name"
        }
    }
}
```
This is because req is empty here when I print it in console.log(), why?

**Comment by templth** [comment]
Hi Chuan,

I can see two causes for this:

* You don't specify the content type header for the payload you sent. So Express can find out a way to convert the content to a JavaScript object

See screenshot: 
![image](https://cloud.githubusercontent.com/assets/558344/8228761/a0f7f3de-15b1-11e5-87a1-7c8813569698.png)

* The JSON payload you sent isn't well-form ;-) But I guess that you will have another error in such case (something like a 415 status code). Here is the payload is used

    {
      "email": "test@test.com",
      "name": "Chuan",
      "location": {
        "latitude": 3333,
        "longitude": 111
      },
      "details": {
        "firstName": "Chuan",
        "lastName": "He"
      }
    }

Hope it helps you!

**Comment by templth** [comment]
A small comment I would have for you is to leverage the Markdown support of Github for comment. This allows you to have more beautiful content ;-) See the following links:

* https://help.github.com/articles/github-flavored-markdown/
* https://guides.github.com/features/mastering-markdown/

This makes things more readable. Feel free to tell me if you have questions.

**Comment by spicypig** [comment]
Thanks Templth, it works! 
Also, I reformatted my Github comment here using markdown. :+1:

**Comment by templth** [comment]
Perfect! ;-)
