### ISSUE TITLE
User form data couldn't be parsed succesfully

### ISSUE THREAD

**Issue by spicypig** [spicypig/carpool#5]
body-parser couldn't parse the request for users/ POST, the req.body is as below:
```JSON
 body: 
   [ { name: 'name', value: 'test' },
     { name: 'email', value: 'test@test.com' } ],
```

I used req.body.name to read "name" from the hash, is there something wrong?

**Comment by templth** [comment]
Yes, it's something normal since you use an array for the body and not an object. Perhaps could you make a try with this:

    body: {
        name: 'test',
         email', 'test@test.com'
    },

With you content, you need to iterate over the array and test the value of the attribute `name`.
